### PR TITLE
Consolidate system sender messages into single message, resolves #14

### LINKED ISSUE #14: Structure of $messages object is not compatible with Googles Gemma 3 models
Hi everyone,

we are currently testing the plugin with multiple LLM models provided by the GWDG and noticed that the adhoc task always fails then using Gemma 3 27B with the following error message:

```
Execute adhoc task: qbank_questiongen\task\generate_questions
Adhoc task id: 147
Adhoc task custom data: {"contextid":82,"sendexistingquestionsascontext":true,"questiongenids":[240,241,242],"uniqadhoctaskid":"6967605c325f9"}
... started 09:22:36. Current memory use 38.2 MB.
[qbank_questiongen] Creating Questions with AI...

[qbank_questiongen] Creating Question 1 ...

Question generation failed. The external LLM returned code 400:
Ein allgemeiner Fehler ist aufgetreten, während versucht wurde, die Anfrage an das KI-Tool zu senden.
Client error: `POST [https://chat-ai.academiccloud.de/v1/chat/completions`](https://chat-ai.academiccloud.de/v1/chat/completions%60) resulted in a `400 Bad Request` response:
{"error":{"message":"Conversation roles must alternate user/assistant/user/assistant/... Conversation roles must alterna (truncated...)
\n#0 /moodle/apache2/htdocs/lib/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create()
#1 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler()
#3 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run()
#5 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /moodle/apache2/htdocs/lib/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /moodle/apache2/htdocs/lib/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 /moodle/apache2/htdocs/lib/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request()
#11 /moodle/apache2/htdocs/local/ai_manager/classes/base_connector.php(191): GuzzleHttp\Client->post()
#12 /moodle/apache2/htdocs/local/ai_manager/classes/manager.php(209): local_ai_manager\base_connector->make_request()
#13 /moodle/apache2/htdocs/question/bank/questiongen/classes/local/question_generator.php(393): local_ai_manager\manager->perform_request()
#14 /moodle/apache2/htdocs/question/bank/questiongen/classes/local/question_generator.php(140): qbank_questiongen\local\question_generator->retrieve_llm_response()
#15 /moodle/apache2/htdocs/question/bank/questiongen/classes/task/generate_questions.php(90): qbank_questiongen\local\question_generator->generate_question()
#16 /moodle/apache2/htdocs/lib/classes/cron.php(523): qbank_questiongen\task\generate_questions->execute()
#17 /moodle/apache2/htdocs/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#18 /moodle/apache2/htdocs/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#19 /moodle/apache2/htdocs/admin/cli/cron.php(186): core\cron::run_main_process()
#20 {main}\n{"error":{"message":"Conversation roles must alternate user/assistant/user/assistant/... Conversation roles must alternate user/assistant/user/assistant/...","type":"BadRequestError","param":null,"code":400}}
... used 22 dbqueries
... used 0.17871403694153 seconds
... used 42.6 MB peak memory
Adhoc task failed: qbank_questiongen\task\generate_questions,Cannot use object of type local_ai_manager\local\prompt_response as array
```
The error message returned by the api `{"error":{"message":"Conversation roles must alternate user/assistant/user/assistant/... Conversation roles must alternate user/assistant/user/assistant/...","type":"BadRequestError","param":null,"code":400}}` led me to the following post by Google on huggingface:
https://huggingface.co/google/gemma-3-27b-it/discussions/42#68b6923c5415c231ace2617a

In short Google's model(s) only supports alternating role messages in the chat messages object. The plugin currently sends 3-4 system role messages followed by one user role message.

Looking at the implementation of of the `question_generator\generate_question()` function it should be technically possible and straightforward to concatenate all the system messages in order to support the model. However I am not sure if this would have deteriorating effects on the performance with other LLM backends.

https://github.com/bycs-lp/moodle-qbank_questiongen/blob/f077e45de0515c9bd87ee596ad68d67ea3324c1b/classes/local/question_generator.php#L61-L157

One could also argue that the structure of the messages object should be as simple as possible before it is forwareded to the `\local_ai_manager\manager` class in order to facilitate easy restructuring fo the `$messages` object by the provider code if necessary.

### PR DESCRIPTION
**Pull request by NJahreis**
I implemented the necessary changes yesterday already as I wanted to test if it makes a difference to the LLM. I did not come up with a good way to test comparatively. Fixes #14 
Tested with Gemma 27B @GWDG.

One could also use newlines for seperation but I don't think it should make any difference to the LLM.

### CODE REVIEW

File: classes/local/question_generator.php [hunk 1]
```diff
@@ -74,20 +74,7 @@ public function generate_question(stdClass $dataobject, bool $sendexistingquesti
...
-                [
-                    'sender' => 'system',
-                    'message' => $instructions,
-                ],
-                [
-                    'sender' => 'system',
-                    'message' => $example,
-                ],
-            ];
+            $systemprompt = $primer . " " . $instructions . " " . $example;
```
Comment (PhMemmel) [inline classes/local/question_generator.php]: if this is being concatenated we need to structure the prompt a bit better.

Please add headings like "## PRIMER", "## INSTRUCTIONS" and "## EXAMPLE XML QUESTION" and include newlines to separate the different sections from each other.

File: classes/local/question_generator.php [hunk 2]
```diff
@@ -106,11 +93,7 @@ public function generate_question(stdClass $dataobject, bool $sendexistingquesti
                     $questiontextsinqbankprompt = 'The question that will be generated by you has to be different '
                         . 'from all of the following questions in this JSON string: "'
                         . json_encode($questiontextsinqbankcat) . '"';
-                    $messages[] =
-                        [
-                            'sender' => 'system',
-                            'message' => $questiontextsinqbankprompt,
-                        ];
+                    $systemprompt = $systemprompt . " " . $questiontextsinqbankprompt;
```
Comment (PhMemmel) [inline classes/local/question_generator.php]: Also here we need a heading like "## ALREADY EXISTING QUESTIONS - THE GENERATED QUESTION MUST DIFFERENT FROM ALL OF THE QUESTIONS IN THE FOLLOWING JSON STRING"

File: classes/local/question_generator.php
Comment (PhMemmel) [inline classes/local/question_generator.php:110]: We also need a heading for the story prompt then

**Review by PhMemmel — CHANGES_REQUESTED** [review]

File: classes/local/question_generator.php [hunk 3]
```diff
@@ -102,37 +95,43 @@ public function generate_question(stdClass $dataobject, bool $sendexistingquesti
...
-                            'sender' => 'system',
-                            'message' => $questiontextsinqbankprompt,
-                        ];
+
+                    $systemprompt .= '\n\n## EXISTING QUESTIONS GENERATED QUESTIONS MUST DIFFER FROM\n' .
+                                    $questiontextsinqbankprompt;
                 }
             }
-
+            $modeheader = '\n\n## QUESTION GENERATION MODE - ';
```
Comment (PhMemmel) [inline classes/local/question_generator.php]: there is no need for the "\n\n" here because this is the first string in the user prompt.

File: classes/local/question_generator.php [hunk 4]
```diff
@@ -102,37 +95,43 @@ public function generate_question(stdClass $dataobject, bool $sendexistingquesti
...
                         $story . '"';
                     break;
                 case story_form::QUESTIONGEN_MODE_STORY:
                 case story_form::QUESTIONGEN_MODE_COURSECONTENTS:
                     $storyprompt =
-                        'Create a question from the following contents. '
-                        . 'Only use this content and do not use any training data: "' . $story . '"';
+                        $modeheader . 'COURSE CONTENTS\n' .
+                        'Create a question from the following contents. ' .
+                        'Only use this content and do not use any training data: "' .
```
Comment (PhMemmel) [inline classes/local/question_generator.php]: I think a new line would be good here, maybe also introduce some delimiters like "### COURSE CONTENT START" and "#### COURSE CONTENT END"

File: tests/local/question_generator_test.php [hunk 5]
```diff
@@ -71,7 +71,8 @@ public function test_generate_question(): void {
         $this->assertEquals($presetjson->primer, $questionobject->primer);
         $this->assertEquals($presetjson->instructions, $questionobject->instructions);
         $this->assertEquals($presetjson->example, $questionobject->example);
-        $expectedstoryprompt = 'Create a question about the following topic. Use your own training data to generate it: "' .
+        $expectedstoryprompt = '\n\n## QUESTION GENERATION MODE - TOPIC\n' .
```
Comment (PhMemmel) [inline tests/local/question_generator_test.php]: if you update the prompt above like suggested in my comment, you will need to remove this here as well: "\n\n"

**Review by PhMemmel — CHANGES_REQUESTED** [review]

**Comment by PhMemmel** [comment]
Hi @NJahreis ,

i added a commit that converts the '\n' literals to real line endings, because the LLM uses real line feeds for "understanding" the structure of the prompt.

I also improved the prompt for course contents and story mode, sorry for leading you in a somehow wrong direction during the review. I had to dig deeper to understand my own code ;-)

My manual tests worked well so far, so I will merge this. Additional feedback as always very welcome.

Thank you very much for your work, very much appreciated! And sorry for the delay.
